import type { Metadata } from "next";
import "./globals.css";
import { Tenor_Sans} from 'next/font/google';

const tenor = Tenor_Sans({
  subsets: ['cyrillic'],
  variable: '--font-tenor',
  weight: ['400', ],
});

export const metadata: Metadata = {
  title: "BTW Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={tenor.className}
      >
        <main className="container mx-auto  min-h-screen">
          {children}
        </main>
        
      </body>
    </html>
  );
}
